# Generated by Django 4.1.2 on 2023-02-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll_number',
            field=models.CharField(default='2100271530036', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
