# Generated by Django 4.1.2 on 2023-02-10 15:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('roll_no', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('employment_type', models.CharField(max_length=100)),
                ('package', models.IntegerField(max_length=10)),
                ('company', models.CharField(max_length=50)),
                ('resources', models.TextField(max_length=500, null=True)),
                ('placement', models.CharField(max_length=9)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
