# Generated by Django 4.1.2 on 2023-02-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_form',
            name='skills',
            field=models.CharField(default='Django', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_form',
            name='package',
            field=models.CharField(max_length=10),
        ),
    ]
