# Generated by Django 4.1.2 on 2023-02-10 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0002_student_form_skills_alter_student_form_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_form',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
    ]
