# Generated by Django 4.1.2 on 2023-02-10 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0003_alter_student_form_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_form',
            name='cgpa',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
