# Generated by Django 4.1.2 on 2023-02-10 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0004_student_form_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_form',
            name='cgpa',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
