# Generated by Django 4.1.2 on 2023-02-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0005_alter_student_form_cgpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_form',
            old_name='roll_no',
            new_name='roll_number',
        ),
    ]
