# Generated by Django 4.1.2 on 2023-02-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0010_searchjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_form',
            name='placement',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='resources',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
