# Generated by Django 4.1.2 on 2023-02-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0011_alter_student_form_placement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_user',
            name='job_title',
            field=models.CharField(default='Backend Developer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchjob',
            name='job_title',
            field=models.CharField(default='Backend Developer', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_form',
            name='job_title',
            field=models.CharField(default='Backend Developer', max_length=100),
            preserve_default=False,
        ),
    ]
