# Generated by Django 4.1.2 on 2023-02-10 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0012_company_user_job_title_searchjob_job_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_form',
            options={'ordering': ['-placement']},
        ),
        migrations.AddField(
            model_name='student_form',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
