# Generated by Django 4.1.2 on 2023-02-10 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0013_alter_student_form_options_student_form_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_form',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 11)),
        ),
    ]
