# Generated by Django 4.1.2 on 2023-02-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0014_alter_student_form_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=20)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
