# Generated by Django 4.1.2 on 2023-02-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0015_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_form',
            name='course',
            field=models.CharField(default='B.TECH', max_length=10),
            preserve_default=False,
        ),
    ]
