# Generated by Django 4.1.2 on 2023-02-11 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0016_student_form_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('stu_no', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
            ],
            options={
                'ordering': ['-stu_no'],
            },
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['-rate']},
        ),
    ]
