# Generated by Django 4.1.2 on 2023-02-11 19:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info_student', '0017_year_alter_skills_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_form',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 12)),
        ),
        migrations.CreateModel(
            name='Email_to_Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=50)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
