# Generated by Django 4.1.2 on 2023-02-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0018_alter_student_form_date_email_to_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_to_companies',
            name='message',
        ),
    ]
