# Generated by Django 4.1.2 on 2023-02-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0019_remove_email_to_companies_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchjob',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='searchjob',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
