# Generated by Django 4.1.2 on 2023-02-12 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0025_alter_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_user',
            name='cgpa',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='searchjob',
            name='cgpa',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
