# Generated by Django 4.1.2 on 2023-02-12 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0026_company_user_cgpa_searchjob_cgpa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={},
        ),
        migrations.AlterField(
            model_name='company_user',
            name='cgpa',
            field=models.FloatField(default=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
