# Generated by Django 4.1.2 on 2023-02-12 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0027_alter_year_options_alter_company_user_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchjob',
            name='cgpa',
            field=models.FloatField(default=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
