# Generated by Django 4.1.2 on 2023-05-07 15:42

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0027_alter_year_options_alter_company_user_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_user',
            name='package',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchjob',
            name='package',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchjob',
            name='cgpa',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='student_form',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
