# Generated by Django 4.1.2 on 2023-02-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0028_alter_searchjob_cgpa'),
    ]

    operations = [
    ]
