# Generated by Django 4.1.2 on 2023-02-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_student', '0029_auto_20230212_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_user',
            name='package',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchjob',
            name='package',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
